drop table flor if exists;
drop table floristeria if exists;
drop table pedido if exists;

create table floristeria (
    id bigint generated by default as identity,
    nombre varchar(255) not null,
    primary key (id)
);

create table flor (
    id bigint generated by default as identity,
    nombre varchar(255) not null,
    color varchar(255) not null,
    primary key (id)
);

create table pedido (
    id bigint generated by default as identity,
    idFlor bigint not null,
    idFloristeria bigint not null,
    primary key (id)
);

alter table pedido
    add constraint flor_pedido_fk
    foreign key (idFlor) references flor;

alter table pedido
    add constraint floristeria_pedido_fk
    foreign key (idFloristeria) references floristeria;

insert into
    floristeria (id, nombre)
    values
    (1L, 'Flores willyrex'), (2L, 'Florecitas super guays Maritrini');

insert into
    flor (id,nombre, color)
    values
    (1L, 'Girasol', 'Verde'), (2L,'Tulipan', 'Rojo'), (3L, 'Lirio', 'Marrón caca');

insert into
    pedido (id, idFlor, idFloristeria)
    values
    (1L, 1L, 1L), (2L, 2L, 1L), (3L, 3L, 1L);