drop table flor if exists;
drop table floristeria if exists;
drop table pedido if exists;

create table pedido (
    id bigint generated by default as identity,
    idFlor bigint not null,
    idFloristeria bigint not null
    primary key (id)
);

create table floristeria (
    id bigint generated by default as identity,
    nombre varchar(255) not null,
    primary key (id)
);

create table flor (
    id bigint generated by default as identity,
    nombre varchar(255) not null,
    color varchar(255) not null,
    primary key (id)
);

alter table pedido
    add constraint flor_pedido_fk
    foreign key (idFlor) references flor;

alter table pedido
    add constraint floristeria_pedido_fk
    foreign key (idFloristeria) references floristeria;

insert into
    floristeria (nombre)
    values
    ('Flores willyrex'), ('Florecitas super guays Maritrini');

insert into
    flor (nombre, color)
    values
    ('Girasol', 'Verde'), ('Tulipan', 'Rojo'), ('Lirio', 'Marrón caca');

insert into
    pedido (idFlor, idFloristeria)
    values
    (1, 1), (2, 1), (3, 1);